set SRC=*.c set CC=gcc set CFLAGS=-Wall -Wextra set IDIRuw=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.c\nset LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.c\n set CC=gcc\n set CFLAGS=-Wall -Wextra\n set IDIR=C:/msys64/ucrt64/include\n set LDIR=C:/msys64/ucrt64/lib\n set SRC=*.c\nset LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp\n set CC=gcc\n set CFLAGS=-Wall -Wextra\n set IDIR=C:/msys64/ucrt64/include\n set LDIR=C:/msys64/ucrt64/lib\n set SRC=*.cpp\n set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp\n set CC=g++\n set CFLAGS=-Wall -Wextra\n set IDIR=C:/msys64/ucrt64/include\n set LDIR=C:/msys64/ucrt64/lib\n set SRC=*.cpp\n set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
set SRC=*.cpp set CC=g++ set CFLAGS=-Wall -Wextra set IDIR=C:/msys64/ucrt64/include set LDIR=C:/msys64/ucrt64/lib set SRC=*.cpp set LIBS=-lm -lSDL3 -lSDL3_image -lSDL3_ttf
